/* wickra-copilot C ABI — generated by cbindgen; do not edit by hand. */

#ifndef WICKRA_COPILOT_H
#define WICKRA_COPILOT_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// A required pointer argument (`handle` or `cmd_json`) was null.
#define WICKRA_COPILOT_ERR_NULL -1

// `cmd_json` was not valid UTF-8.
#define WICKRA_COPILOT_ERR_UTF8 -2

// A panic was caught at the FFI boundary.
#define WICKRA_COPILOT_ERR_PANIC -3

// An opaque handle to a copilot instance. Created by [`wickra_copilot_new`] and
// destroyed by [`wickra_copilot_free`]; never dereferenced by the caller.
typedef struct WickraCopilot WickraCopilot;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Construct a copilot from a spec JSON string (`""` or `"{}"` for an empty
// handle whose spec is set later via a `set_spec` command).
//
// Returns an opaque handle, or null if `spec_json` is null, not valid UTF-8, or
// not a valid spec. Free the handle with [`wickra_copilot_free`].
//
// # Safety
// `spec_json` must be null or a valid NUL-terminated C string.
WickraCopilot *wickra_copilot_new(const char *spec_json);

// Destroy a copilot handle. Null is a no-op.
//
// # Safety
// `handle` must be null or a handle previously returned by
// [`wickra_copilot_new`] and not already freed.
void wickra_copilot_free(WickraCopilot *handle);

// Apply a command JSON and write the response JSON into the caller's buffer.
//
// Returns the response length in bytes (excluding the terminating NUL), or a
// negative error code. When the return value `len` satisfies `len < cap`, the
// response and a trailing NUL have been written to `out`; otherwise `out` is
// left untouched and the caller should re-call with a `cap` of at least
// `len + 1`. Pass `out = NULL`, `cap = 0` to query the length without writing.
//
// # Safety
// `handle` must be a valid handle; `cmd_json` a valid NUL-terminated C string;
// `out` either null or a writable buffer of at least `cap` bytes.
int32_t wickra_copilot_command(WickraCopilot *handle,
                               const char *cmd_json,
                               char *out,
                               uintptr_t cap);

// The library version as a static NUL-terminated string (do not free).
const char *wickra_copilot_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WICKRA_COPILOT_H */
